USE TIMETRACKING;

-- Inserindo tipos de registro padrões
INSERT INTO TIMETRACKING.TIPO_REGISTRO VALUES (1, 'Entrada');
INSERT INTO TIMETRACKING.TIPO_REGISTRO VALUES (2, 'Saída');

-- Inserindo tipos de período padrões
INSERT INTO TIMETRACKING.TIPO_PERIODO VALUES (1, 'Matutino');
INSERT INTO TIMETRACKING.TIPO_PERIODO VALUES (2, 'Vespertino');

-- Inserindo usuário
INSERT INTO TIMETRACKING.USUARIO VALUES (1, 'Angleby Vamberg')
